#GROQ_API_KEY = '<enter API key here>'

# Instructions to get API key:
# 1) Go to https://console.groq.com/keys
# 2) Create an API key
# 3) Copy the API key when displayed
# 4) Place within the quotation marks of GROQ_API_KEY
# 5) Uncomment the GROQ_API_KEY line by removing the hashtag symbol behind it

# NOTES:
# - Please enter the API key WITHIN THE QUOTATION MARKS
# - Ensure this TOML file remains in the config/ directory
